Второй этап Дипломной работы
IcelandicMan/java-explore-with-me pull request #3
Opened 2023-12-02 23:20 UTC by IcelandicMan

2023-12-03 20:37 UTC, YazykovMikhail requested changes

2023-12-03 20:37 UTC, YazykovMikhail commented on ewm-service/src/main/java/ru/practicum/controller/AdminController.java
> +@RequestMapping(path = "/admin")
Контролеры делаебтся на основании сущностей, админ это доступ.
Поэтому должны быть отдельные классы(контроллеры):
CategoryAdminController
EventAdminController
UserAdminController
они будут в папке admin
дальше контроллеры для private, public аналогичным образом.

2023-12-03 20:37 UTC, YazykovMikhail commented on ewm-service/src/main/java/ru/practicum/controller/AdminController.java
> +    @PostMapping("/users") // 1
/1 странные комеентарии, комментарии должны о чем то говорить/подсказывать, а в этих нет смысловой нагрузки, лучше убрать

2023-12-03 20:37 UTC, YazykovMikhail commented on ewm-service/src/main/java/ru/practicum/service/event/EventServiceImpl.java
> +    private final ObjectMapper objectMapper = new ObjectMapper();
private final ObjectMapper objectMapper;
внедрением завивисмостей занимается Spring, незабывай, сделай папку конфиг и там создай @Bean что бы он мог сюда внедриться 
(и в другие места)

2023-12-03 20:57 UTC, IcelandicMan commented on ewm-service/src/main/java/ru/practicum/controller/AdminController.java
> +    @PostMapping("/users") // 1
Да, совсем забыл их удалить. Это их нумеровал, чтобы сверяться со своим списком в тетради :)

2023-12-03 22:07 UTC, IcelandicMan commented on ewm-service/src/main/java/ru/practicum/controller/AdminController.java
> +@RequestMapping(path = "/admin")
Понял! Но на самом деле я в принципе хочу поменять всю структуру размещения классов, то что я выбрал в начале показалась, мне хорошей, но позже разонравилась :)

2023-12-03 22:08 UTC, IcelandicMan commented on ewm-service/src/main/java/ru/practicum/service/event/EventServiceImpl.java
> +    private final ObjectMapper objectMapper = new ObjectMapper();
добавлен класс для конфигурации ObjectMapper objectMapper

2023-12-05 07:12 UTC, YazykovMikhail approved these changes

2023-12-05 11:08 UTC, merged